### ISSUE TITLE
Write protect blocking all bios options on HP Chromebook 14-ak050nr

### ISSUE THREAD

**Issue by jaszhix** [MattDevo/scripts#1]
Setting boot options, hardware ID, or updating legacy BIOS presents this error:

```Write-protect enabled, non-stock firmware installed, or not running ChromeOS; cannot set boot options.```

@MattDevo I saw you post a [comment](https://www.reddit.com/r/chromeos/comments/49y0hy/boot_from_usb_on_hp_chromebook_14/d0xh0r0) in /r/chromeos saying Bay Trail devices don't need to remove the write protect screws to get the script working - I wonder if this is an exception?

ChromeOS info -

Version 49.0.2623.95 (64-bit)
Platform 7834.60.0 (Official Build) stable-channel kip
Firmware Google_Kip.5216.227.25

I am using developer mode.

Thanks for writing these scripts.

**Comment by MattDevo** [comment]
Setting the boot options and hardware ID both require the WP to be
disabled, but updating the legacy boot payload does not. If you're getting
that error for updating the legacy boot, I may need you to do a little
troubleshooting with me to figure out why it's throwing that error.

**Comment by jaszhix** [comment]
I rebooted and tried to selected the update legacy bios option first this time, and I got a different error.

Unknown or unsupported device (kip); cannot update Legacy BIOS.

**Comment by MattDevo** [comment]
was "kip" in all lower case?  I'm expecting the first letter to be 
capitalized for the string comparison, since all other board names are.  
That's the only reason I can thing that you're getting that error.  But 
I've had other kip owners use the script without issue so I'm slightly 
puzzled

**Comment by jaszhix** [comment]
I currently have crouton installed, and a root password set - would that affect anything?

**Comment by MattDevo** [comment]
nope, wouldn't affect anything.  my script contains a list of device 
names for each type (eg, baytrail, haswell, etc) so it can determine the 
correct firmware to flash for each device.  Kip is listed in the 
baytrail group, so unless it's a case-sensitivity issue, unsure why it 
wouldn't be correctly identified

**Comment by jlwilliams3rd** [comment]
I am having the same issue I have this model hp "HP Chromebook 14-ak050nr 14-Inch Laptop (Intel Celeron, 4 GB RAM, 16 GB SSD)"  When I try the Update Legacy BIOS option i get "Unknown or unsupported device (kip); cannot update Legacy BIOS"

**Comment by MattDevo** [comment]
ok, looks like a case-sensitivity issue, I'll try and fix that later today

**Comment by jlwilliams3rd** [comment]
Awesome! I'll be waiting :D

**Comment by MattDevo** [comment]
should be fixed now

**Comment by jlwilliams3rd** [comment]
Awesome worked for me!
