### ISSUE TITLE
Better Checking Mechanism for UEFI vs. BIOS OS Installs.

### ISSUE THREAD

**Issue by ReddestDream** [MattDevo/scripts#14]
It should be possible to automatically determine which firmware type a user should use and at least suggest this during the install process. Perhaps GPT vs. MBR on the SSD could be examined or we could check for the presence of /sys/firmware/efi. Perhaps RW_Legacy could even be suggested if a user is on ChromeOS, just wants Linux, and doesn't want to remove the screw. Food for thought. I'll look into good ways to test. Thanks.

**Comment by 3rdwiki** [comment]
Note there is a fiverr for this on [bountysource](https://www.bountysource.com/trackers/18157215-mattdevo-scripts).
