### ISSUE TITLE
firmware-util.sh: ./firmware.sh: line 8: syntax error: unexpected "("

### ISSUE THREAD

**Issue by CaTzil** [MattDevo/scripts#16]
running that on Liberelec
curl -L -O http://mrchromebox.tech/firmware-util.sh && bash firmware-util.sh

**Comment by MattDevo** [comment]
You can't run these scripts from OpenELEC/LibreELEC because they don't have an actual Bash shell.  This is noted on the Kodi wiki page as well as the Firmware Utility Script page.
