### ISSUE TITLE
USB device detection with mmc

### ISSUE THREAD

**Issue by darkdragn** [MattDevo/scripts#17]
Let me just start by saying that I love your work, and I admire how far you've taken your support.

I recently received a Dell Chromebook 11 3120 (CANDY) and in flashing the firmware with your scripts I discovered that your scripts could not see my USB devices. I traced the issue out to line 95 in your funstions.sh, which reads the following:

`[[ -f /dev/mmcblk0 ]] && intStor="/dev/mmcblk0" || intStor="/dev/sda"`

Even though the device uses /dev/mmcblk0 the check is failing because -f in bash only returns true if the target is a regular file. For that test to return true, you need the -f to be a -b, since -b returns true if the target is a block special file. I will put the corrected line below:

`[[ -b /dev/mmcblk0 ]] && intStor="/dev/mmcblk0" || intStor="/dev/sda"`

I pulled your script down, commented out the download and remove lines and tested it. It works, so please update the script. I'm sorry I don't have the time to create a commit and set up a pull request since I'm heading into work, it makes me feel like I'm being lazy. Sorry.

Have a great evening.

**Comment by MattDevo** [comment]
fixed / committed, thanks
