### ISSUE TITLE
Latest scripts won't run

### ISSUE THREAD

**Issue by gotaug** [MattDevo/scripts#21]
firmware.sh returns:
8: Syntax error: "(" unexpected

firmware-util.sh returns:
33 [[: not found
33 0: not found
33 0: not found
35: source: not found
36: source: not found
37: source: not found
40: prelim_setup: not found
41: [[: not found
44: menu_fwupdate: not found

I've tried running them in bash and from the command line with the same results.

If the error is on my part, please set me straight.  I've searched for solutions and haven't been able to get any different result.

Thanks,
</Aug==---

**Comment by MattDevo** [comment]
exact command line used and OS from which being run?

**Comment by gotaug** [comment]
I  put everything on a USB stick, opened the terminal (Ctrl+Alt+F3) mounted it and tried running the files (firmware-util.sh and firmware.sh) from the USB drive. That was how I got the errors.

However,  I just found the following command:
cd; curl -L -O http://mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh

It is running now and seems to be working like a charm.  I was gonna let you know about finding that command, and instead I discovered you'd already replied to my issue report.

I've got an Acer C740 and it boots to Shell> now.

How do I enter the bios or get the option to select a boot device such as USB?

I'm impressed by your quick and concerned response.  

Thanks,
</Aug==---

**Comment by gotaug** [comment]
Got it!  I wasn't hitting Ctrl + L fast enough!

**Comment by musiqbonez** [comment]
Hello Guru's I'm having trouble installing updated script SeaBios on nephews chromebook. I was able to turn off developer mode and I too get the 2 beeps after enable_dev_usb_boot

**Comment by MattDevo** [comment]
@musiqbonez what exactly is the issue?  dev_boot_usb has nothing to do with Legacy Boot mode / SeaBIOS.  dev_boot_legacy is automatically set when updating the RW_LEGACY firmware via the script.

**Comment by musiqbonez** [comment]
@MattDevo Im getting the two beeps after Ctrl + U meaning there is no SeaBios on this chromebook

**Comment by MattDevo** [comment]
@musiqbonez CTRL+L is used for Legacy Boot Mode / SeaBIOS, not CTRL+U.  On Intel Chromebooks, CTRL+U is used to boot ChromeOS/ChromiumOS from USB, nothing else

**Comment by musiqbonez** [comment]
my apologies I meant CTRL-L @MattDevo

**Comment by MattDevo** [comment]
@musiqbonez what device are you using, and did you already update the RW_LEGAYC firmware via my script?

**Comment by musiqbonez** [comment]
@MattDevo i was trying to access RW_LEGACY firmware via your script but not sure fairly new to this. I tried coping it but it doesnt work

**Comment by musiqbonez** [comment]
@MattDevo its a Hp Chromebook Memory 4 GB (Ram)
Intel processor screen size 11.6" 16 GB eMMC

**Comment by MattDevo** [comment]
@musiqbonez what device/board name does the script report when you run it (it's in parentheses after the device name)?  What do you mean by 'tried copying it'?  The script is run from a terminal shell using the command listed on the website.  From the menu presented, you select option 1 for RW_LEGACY firmware

**Comment by musiqbonez** [comment]
I see your script Flash RW_LEGACY with 1185 lines is to be typed in

**Comment by MattDevo** [comment]
@musiqbonez I don't understand what you're trying to do.  You don't run any of the scripts directly from this github repository.  You run it using the command listed on my website at https://mrchromebox.tech/#fwscript.

**Comment by musiqbonez** [comment]
Not sure if I'm in the right area. It's prompting me for a Login and passwd which chronos followed by sudo bash seems to get me a couple steps but after that I'm lost just graduated school and still not to savy on all this yet sorry

**Comment by musiqbonez** [comment]
How do I get to the terminal/shell is that what the picture I sent you is.

**Comment by MattDevo** [comment]
@musiqbonez this is very straightforward:
- power on your device
- log in to ChromeOS (guest is fine)
- open link to my Firmware Utility script linked above
- open shell terminal via CTRL+ALT+T, then type 'shell' and press enter
- copy script command from website, paste into shell
- select option 1 for RW_LEGACY firmware update
- reboot, hit CTRL+L for legacy boot mode

I don't know what picture you are referring to, there's nothing embedded in any of your posts

**Comment by musiqbonez** [comment]
It's asking for a local host login:

**Comment by MattDevo** [comment]
@musiqbonez not if you follow those steps

**Comment by musiqbonez** [comment]
Really appreciate you taking the time out of your busy day to assist me. Thanks A Million

**Comment by musiqbonez** [comment]
Ok I will try this

**Comment by musiqbonez** [comment]
RW_LEGACY firmware successfully installed/updated  awesome

**Comment by musiqbonez** [comment]
It looks like I need a 86x windows 10 OS instead 64x OS I was able to see the windows 10 logo after hitting CTRL-L but in gave a error message 3sec later your pc ran into a problem

**Comment by MattDevo** [comment]
@musiqbonez you can't install Windows via RW_LEGACY, you need the UEFI Full ROM for that. Again, what device are you using?

**Comment by ReddestDream** [comment]
@MattDevo C740, right @musiqbonez?

**Comment by musiqbonez** [comment]
Product:	HP Chromebook 11-v010nr ALL
Serial number:	8CG6431ZLN
Product number:

**Comment by ReddestDream** [comment]
@musiqbonez This?

http://store.hp.com/us/en/pdp/hp-chromebook---11-v010nr-(energy-star)

This is Braswell, (N30xx). We don't have a Full ROM for that yet, so you won't be able to install Windows on it ATM. We have a Braswell Chromebook we are currently working on, but we don't have anything ready for release yet.

**Comment by musiqbonez** [comment]
Ok understandable thanks for the help
