### ISSUE TITLE
i keep getting cheksom error

### ISSUE THREAD

**Issue by rmtx83** [MattDevo/scripts#212]
also i have an acer cb11-9h
i keep getting this error please help 
Firmware download checksum fail; download corrupted, cannot flash.

**Comment by MrChromebox** [comment]
> also i have an acer cb11-9h

this doesn't help me - please provide a picture of the main menu, as well as the error (so I can see what file it should be downloading, as well as what file it is trying to download)

**Comment by rmtx83** [comment]
![Screenshot 2022-07-12 4 43 10 PM](https://user-images.githubusercontent.com/105466122/178600630-03583fd6-f168-4dad-b63d-6671b8fd37e9.png)
![Screenshot 2022-07-12 4 42 40 PM](https://user-images.githubusercontent.com/105466122/178600639-e036879b-ccbe-434a-aafa-d2e52900ea65.png)

**Comment by rmtx83** [comment]
is this what you wanted

**Comment by MrChromebox** [comment]
your device is completely unrecognized. Did you something stupid like change/clear the HWID?

**Comment by rmtx83** [comment]
no not that im aware of

**Comment by MrChromebox** [comment]
< The script clearly offers option 4 allowing you to set the correct hardware ID. Set the correct ID and then try to download and install the firmware.

this is only useful if the user knows the correct hardware ID for the device, which the OP clearly does not

**Comment by MrChromebox** [comment]
@rmtx83 what is the history of this device? Clearly it's not a new, unmodified device.

**Comment by ferrellsl** [comment]
> acer cb11-9h

Can he not derive a hardware ID based on the brand/model?

**Comment by MrChromebox** [comment]
> Can he not derive a hardware ID based on the brand/model? I think he left out a digit, probably should be an Acer CB311-9H.

nope

**Comment by MrChromebox** [comment]
as long as the board name is the same, yes. Not like they are going to make the problem any worse at this point

**Comment by ferrellsl** [comment]
> as long as the board name is the same, yes. Not like they are going to make the problem any worse at this point

What's the easiest way to extract the ID now that I'm running Ubuntu 22 with your latest UEFI firmware?  Re-running your UEFI firmware installation script just shows options for updating/re-installing the firmware or reverting back to stock.  I didn't notice any option to display the ID.

**Comment by MrChromebox** [comment]
> What's the easiest way to extract the ID now that I'm running Ubuntu 22 with your latest UEFI firmware? 

you can't, it doesn't exist in the UEFI firmware. It's a component that only exists in the stock CrOS firmware.
you can extract it from the backup you made on USB though, using the CrOS gbb_utility

**Comment by ferrellsl** [comment]
Ah, OK.  In this case wouldn't it just be easier to grab a stock firmware file and flash that to the affected system and then install your UEFI firmware?  If so, I have the stock firmware file for a system I recently returned to the store due to an audio failure.....I blew the speakers due to enabling over amplification in Ubuntu. Firmware file attached.

[stock-firmware-BOBBA-20220609.zip](https://github.com/MrChromebox/scripts/files/9106792/stock-firmware-BOBBA-20220609.zip)

**Comment by rmtx83** [comment]
> @rmtx83 what is the history of this device? Clearly it's not a new, unmodified device.

its a chromebook that i powerwashed not to long ago and put in to full dev mode

**Comment by rmtx83** [comment]
im a little confused here

**Comment by rmtx83** [comment]
i dont do stuff like this there are no tutorials for my device

**Comment by rmtx83** [comment]
> 

how to i flash this

**Comment by MrChromebox** [comment]
you don't.

Boot your device to recovery mode. Tell me what it reports as the board name/model at the bottom. post a pic if unsure.

**Comment by rmtx83** [comment]
ok so i use esc and refresh ill tell you what i see

**Comment by rmtx83** [comment]
ok i dont have my phone i will do it in parts

**Comment by rmtx83** [comment]
c2a

**Comment by rmtx83** [comment]
ok droid c2p ab3

**Comment by MrChromebox** [comment]
I need to know the full string, exactly -- in the correct case, all spaces, dashes, etc exactly as on screen

**Comment by rmtx83** [comment]
how strange it says my divice is a c14 now
even tho my sticker on my chromebook says cb311

**Comment by rmtx83** [comment]
its  DROID C2P-A3B-E2S-B2K-A7B-A8P

**Comment by MrChromebox** [comment]
ok, that's a perfectly valid HWID. There's no reason the script shouldn't identify your device properly...

**Comment by rmtx83** [comment]
before it said unregonized and now its says acer chromebook 314 droid
even tho i have a cb311

**Comment by rmtx83** [comment]
do you want me to try to flash it again

**Comment by MrChromebox** [comment]
I don't want you to flash anything, just run the script and check the main menu heading to see if your device is identified properly

**Comment by rmtx83** [comment]
![Screenshot 2022-07-14 11 35 21 AM](https://user-images.githubusercontent.com/105466122/179032780-962cb358-258d-4814-bc8f-bed964492f92.png)

**Comment by rmtx83** [comment]
i have cb311 not 314

**Comment by MrChromebox** [comment]
doesn't matter, all that matters is that your board name is correctly identified (DROID)

**Comment by rmtx83** [comment]
yes it says droid what should i do now

**Comment by MrChromebox** [comment]
what are you trying to do?

**Comment by rmtx83** [comment]
im trying to install a different os

**Comment by rmtx83** [comment]
cus chrome os sucks

**Comment by MrChromebox** [comment]
that's what the UEFI Full ROM firmware is for. Read the documentation on the chrultrabook subreddit/Discord for Windows support.

**Comment by rmtx83** [comment]
ok byeee
