### ISSUE TITLE
Fail to boot GalliumOS after bios update

### ISSUE THREAD

**Issue by madsheilskov** [MattDevo/scripts#22]
I have a dual boot ChromeOS / GalliumOS on a Dell 13 Chromebook using Legacy boot mode from the https://mrchromebox.tech/#fwscript page.. 
Today, while booting GallioumOS asked me to update BIOS (Why would it do this ?). Hereafter the chromebook is hanging at "SeaBIOS (Version rel-1.10.0.6-g3f40bbd-MrChromebox-2016.11.07) // Botting from hard disk ....
I have no idea how to get out of this.

UPDATE:
Booting with USB device enables "ESC for boot menu"  and get two boot device options hard-disk and USB. Hard disk hangs and if selecting USB I get a GRUB error: unknown filesystem. Entering rescue mode // grub rescue >

UPDATE2:
Booting from another USB with my chromeOS recovery (I think). When booting from this it prints vmlinuz.A.................. then goes into chromeOS start screen but eventually falls back into the SeaBIOS (version....) screen.

**Comment by MattDevo** [comment]
I'm really confused here.  GalliumOS would never ask you to update the firmware -- it has no idea what firmware you're running / no way to know you'd need an update.  More likely is that there was a msg related to firmware for integrated video or WiFi that you misinterpreted.

Anyways, I'm not sure what happened, but likely the easiest solution is to boot GalliumOS on USB and reinstall grub (the bootloader) which appears to be missing or damaged.  Your best resource for doing that is on the GalliumOS subreddit or IRC channel
