### ISSUE TITLE
Link here from mrchromebox.tech broken

### ISSUE THREAD

**Issue by The1andONLYdave** [MattDevo/scripts#23]
Hi, 
the link in the last part of the text* at https://mrchromebox.tech/#fwscript is broken, it redirects to https://github.com/MattDevo/scripts+%20target= giving a github 404.

[*]"The source for the Firmware Utility Script (as well as all helper/accessory scripts) can be found on my 'scripts' github repository. Any issues, feature requests, and/or improvements can be reported via the issue tracker or a pull request."

**Comment by ReddestDream** [comment]
Can confirm.

**Comment by MattDevo** [comment]
link fixed
