### ISSUE TITLE
Legacy boot not working on Kefka

### ISSUE THREAD

**Issue by plooney** [MattDevo/scripts#29]
I posted the following to Reddit for Gallium OS. 

https://www.reddit.com/r/GalliumOS/comments/61ezwi/dell_chromebook_11_3180_kefka_not_loading_seabios/

I have used your script but legacy boot seems to have a problem on KEFKA

**Comment by MattDevo** [comment]
this isn't an issue with the script, please file it under[ firmware issues](https://github.com/MattDevo/firmware/issues) where it belongs
