### ISSUE TITLE
Integrity of downloaded files

### ISSUE THREAD

**Issue by lgierth** [MattDevo/scripts#3]
I don't feel comfortable executing code without verifying its integrity. @MattDevo I somewhat trust you with compilation of these tools, but I don't trust Dropbox. Could you add verification of SHA256 hashes to the scripts, or alternatively commit them to the git repo?

**Comment by lgierth** [comment]
Or just a list of hashes would already be a big help!

**Comment by MattDevo** [comment]
The files are all md5 checksummed when built, and verified after
downloading / before flashing

**Comment by lgierth** [comment]
Oh I see now, had somehow overlooked that -- The .md5 files don't help me a lot though, because they're downloaded from the same untrusted source. Could you post an md5 list of the dropbox directory? That'd be tremendously helpful. I just don't want my new laptop to be owned right from the start :)

**Comment by MattDevo** [comment]
posting a md5 of the directory wouldn't be useful given how often I throw
test builds in there etc.  I'll have to figure something out that's not
overly cumbersome for testing use as well as releases

**Comment by MattDevo** [comment]
all files are downloaded from my own domain/server, https://mrchromebox.tech, and like before are md5sum checked after download by the script
