### ISSUE TITLE
UEFI firmware will not save boot order settings

### ISSUE THREAD

**Issue by MeatL0af** [MattDevo/scripts#35]
hi

-have a ASUS Chromebox CN60 - was previously running Legacy Seabios with a standalone install of Libreelec
-desired to update to krypton Libreelec standalone - 
-installed / updatyed to the latest UEFI firmware via the firmware utility script from a linuxlive on teh chromebox
- reinstalled a fresh Libreelec stand alone
- issue is that the default boot order is USB first - then HDD internal
- I enter the firmware via the ESC button - i chaneg tie boot order F10 save = Y then exit - all seems good
- upon a reboot the boot order reverts back to the USB first and sometime just hangs onthe bunny screen  - cycle power clears the issue hit ESC - enter the firmware change order boot HDD - boots the OS fine - however upon a reboot the same

**Comment by ReddestDream** [comment]
Known issue. See here:

https://github.com/MattDevo/firmware/issues/10
