### ISSUE TITLE
Error downloading cbfstool;cannot proceed

### ISSUE THREAD

**Issue by subbaiya** [MattDevo/scripts#39]
Im facing this error "Error downloading cbfstool;cannot proceed" after suing the command cd; curl -LO https://mrchromebox.tech/setup-kodi.sh && sudo bash setup-kodi.sh
![error snap](https://user-images.githubusercontent.com/30260921/28314568-b453b830-6bd8-11e7-8cfc-cc4fa35027f8.jpg)

**Comment by MattDevo** [comment]
was a SSL cert issue, fixed now

**Comment by subbaiya** [comment]
Really You done a great job man... Now the rom installed without errors....

*Regards*

*I. Subbaiyan*
