### ISSUE TITLE
Gandof Core boot flash showing black screen

### ISSUE THREAD

**Issue by sonkatech** [MattDevo/scripts#4]
Hey Matt,

Thanks for your work. I'm using the 2015 Toshiba CB2 Gandof with a recent upgrade of an ssd. Installing John's seabios worked successfully but I couldn't get past the gfxboot error. 

Where I installed his RW legacy script. Rebooting I get the same gfxboot error. So I try installing the core boot script (double checked it's for Gandof). I made a backup of the current core boot on a flash drive. Script installs successfully. 

Upon reboot screen flashes to John's seabios, then black, then the attached image below. After just black screen. 

So I'm kinda lost now... how can I revert my actions? Since gfxboot error won't go away, I might just install gallium and install Ubuntu 16.04 from there. 

Thank you﻿

**Comment by MattDevo** [comment]
issue not script/firmware related, resolved on G+
