### ISSUE TITLE
[Kodi Script] Make it so you can remove the 2nd OS from the menu

### ISSUE THREAD

**Issue by MrDiamond123** [MattDevo/scripts#40]

**Comment by MattDevo** [comment]
No idea what you're referring to -- can you provide more detail?

**Comment by MrDiamond123** [comment]
In the menu of the Kodi Script add a option to remove Ubuntu/GalliumOS/Kodi and the partition.

**Comment by MattDevo** [comment]
The ChromeOS recovery process will reset the partitions on the internal storage to stock, there's no reason for the script to duplicate functionality that already exists

**Comment by MrDiamond123** [comment]
Oh...

**Comment by MattDevo** [comment]
http://kodi.wiki/view/Chromebox#Resetting_to_Stock

**Comment by MrDiamond123** [comment]
@MattDevo What is the partition does the script use? I am going to format it my self

**Comment by MattDevo** [comment]
@MrDiamond123 partitions 6 and 7 (KERN-C and ROOT-C), which are devices /dev/sda6 and /dev/sda7 (or /dev/mmcblk0p6 and /dev/mmcblk0p7 if your device uses eMMC instead of a SSD)

**Comment by MrDiamond123** [comment]
k thanks
