### ISSUE TITLE
graphics initialization failed

### ISSUE THREAD

**Issue by jbhouse** [MattDevo/scripts#43]
Sorry if this is not the right place for this
Anyway, I selected script 1 to run on my Samsung3 Chromebook. when I ctrl + L'd at the developer boot screen and attempt to boot from my usb (which has ubuntu 16.04) on it i get an error that says- graphics initialization failed
I have crouton installed which is what i usually use for coding, and I can't think of any other irregularities with my system. Again, sorry if this isn't the place for this but I have no idea how to troubleshoot this as I'd love to be able to truly dual boot a linux environment instead of using crouton

**Comment by MattDevo** [comment]
that's a known issue with the version of gfxboot/grub used on the Ubuntu 16.04 ISO.  Use GalliumOS 2.1 (which is a Xubuntu derivative optimized for ChromeOS hardware) and it should work fine
