### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by tygamer1234** [MattDevo/scripts#45]
I have bash for Windows, but the firmware-util cannot determine my PC model. My Windows says it's WINKY.

**Comment by ReddestDream** [comment]
These scripts do not support WSL on Windows. WSL doesn't allow low enough access.

For firmware updates on Windows, use the Windows Firmware Backup/Update/Flashing Tool here:

https://www.reddit.com/r/chrultrabook/comments/6nesge/windows_firmware_backupupdateflashing_tool/

**Comment by tygamer1234** [comment]
Could you provide firmware and BIOS for winky? If not, thanks anyway.

**Comment by ReddestDream** [comment]
Winky is BayTrail and BIOS updates are supported on Windows with the tool I linked you to above.

**Comment by tygamer1234** [comment]
Oh OK, thank you.
