### ISSUE TITLE
Error get_flashrom_ups: command not found on an ASUS C300SA ?

### ISSUE THREAD

**Issue by e-dot** [MattDevo/scripts#47]
Hello,
I tried to launch firmware-util.sh and got the following error :
  `./function.sh: line 465: get_flashrom_ups: command not found`

The model is an ASUS C300SA (HWID TERRA F2P-F4S-V5Q-B3A-A3M, Platform Braswell).

Can you please advise on how to fix this?

Regards,

E.

**Comment by MattDevo** [comment]
fixed
