### ISSUE TITLE
Updating libreelec and kodi manually

### ISSUE THREAD

**Issue by ervy1** [MattDevo/scripts#51]
Hi,
Not sure i'm in the right place - I managed to install and run your script to get a standalone LE/kodi on usb stick for testing in my HP Chromebox. I would like upgrade libreelec 8.0.2 to a latest testbuild version (kodi 18) for testing but unsure where to place the update tar file as there is no update folder at least none i can see via file manager. Is there a path I can follow at the root level? I'm running LE 8.0.2 with kodi 17.3 Tnx.

**Comment by MattDevo** [comment]
https://wiki.libreelec.tv/how_to/update_libreelec
