### ISSUE TITLE
I think I broke grub

### ISSUE THREAD

**Issue by Sazazar** [MattDevo/scripts#53]
My acer 11 chromebook has ran into something I hope I can fix fast. I cannot boot into anything at all. It says <error: no such device: 5f1be668-aeb1-4af0-b6a4-2b3b151b3092.> then it enters grub rescue and I don’t know how it works. I’m currently using the uefi script by mr.chrombox

**Comment by MattDevo** [comment]
this is a grub/OS-related issue, not a firmware-related one,  You'll need to boot another Linux USB and repair grub; repair instructions may be specific to whatever distro you are running
