### ISSUE TITLE
stumpy firmware link is doa

### ISSUE THREAD

**Issue by bi0tech** [MattDevo/scripts#7]
The source for the stumpy firmware from the sources script is coming up dry.  Not sure if there was an updated version or if it just vanished.

https://dl.dropboxusercontent.com/u/98309225/coreboot-seabios-stumpy-20160623-mattdevo.rom

**Comment by MattDevo** [comment]
fixed, filename wasn't corrected at last update

**Comment by bi0tech** [comment]
What is the correct name for stumpy?  Tried 0704, 0710, 0711 for giggles, but still nada.

**Comment by MattDevo** [comment]
I don't recommend flashing directly, but if you're insistent on doing so, just look at the corrected filename in sources.sh.

**Comment by bi0tech** [comment]
That's the problem though sources.sh references a file link that doesn't exist.

**Comment by MattDevo** [comment]
whoops, forgot to push the commit.  should be fixed now for reals, but plz use the script to flash

**Comment by bi0tech** [comment]
Ill give it go.  Wanted to get it put back together before the cat finds where I have all the pieces.
